version: "3.8"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception
    restart: always

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception
    restart: always

  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build:
      context: ./requirements/nginx
    volumes:
      - wordpress_volume:/var/www/html
    env_file:
      - ./.env
    ports:
      - "443:443"
    networks:
      - inception
    restart: always

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/taehkwon/data/mariadb"
      o: "bind"
  wordpress_volume:
    driver: local
    driver_opts:
      type: "none"
      device: "/home/taehkwon/data/wordpress"
      o: "bind"

networks:
  inception:
    driver: bridge
