FROM debian:buster

# Nginx와 OpenSSL 설치
RUN apt-get update && \
    apt-get install -y nginx openssl

# SSL 인증서 디렉터리 생성
RUN mkdir -p /etc/nginx/ssl

# Nginx 설정 파일 복사
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

# Nginx 실행을 위한 포트 노출
EXPOSE 443

# Nginx 시작
CMD ["nginx", "-g", "daemon off;"]
